---
- hosts: localhost
  vars_files:
    - vars/pvc-destination-gen.yml
    - vars/storage-class-mappings.yml
  tasks:
    - name: Verify required variables are defined
      assert:
        that:
          - pvc_data_filepath is defined

    # -------
    - block:
        - name: Ensure pvc data file exists
          stat:
            path: "{{ pvc_data_filepath }}"
          register: p

        - debug: msg="PVC json file exists..."
          when: p.stat.exists

        - fail:
          when: p.stat.exists == False

        - name: Ensure namespace data file exists
          stat:
            path: "{{ namespace_data_filepath }}"
          register: n

        - debug: msg="Namespace json file exists..."
          when: n.stat.exists

        - fail:
          when: n.stat.exists == False


        - set_fact:
            pvc_data: "{{ lookup('file', pvc_data_filepath) | from_json }}"
            namespace_data: "{{ lookup('file', namespace_data_filepath) | from_json }}"


    - name: ensure the namespaces are created for the pvcs
      k8s:
        state: present
        definition: "{{ lookup('template', 'namespace.yml.j2') }}"
      loop: "{{ namespace_data }}"

    - name: "Parsing pvc data"
      set_fact:
        mig_dest_pvc_data: []

    - name: "Converting pvc data"
      set_fact:
        mig_dest_pvc_data: "{{ mig_dest_pvc_data + [(item | combine(mig_converted_sc, recursive=true))] }}"
      vars:
        mig_converted_sc:
          storage_class: "{{ mig_storage_class_mappings.get(item.storage_class+'_'+('RWX' if 'ReadWriteMany' in item.access_modes else ('ROX' if 'ReadOnlyMany' in item.access_modes else 'RWO')), item.storage_class)}}"
      loop: "{{ pvc_data }}"

    - name: ensure the pvcs are created on destination
      k8s:
        state: present
        definition: "{{ lookup('template', 'pvc.yml.j2') }}"
      loop: "{{ mig_dest_pvc_data }}"
