apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssh
  name: ssh
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
  selector:
    app: ssh
  type: LoadBalancer
