apiVersion: v1
kind: Pod
metadata:
  name: ssh-rsync
  labels:
    app: ssh
spec:
  containers:
  - name: myapp-container
    image: quay.io/pranavgaikwad/unpriv-ssh:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 2222
      name: ssh
      protocol: TCP
